# Generated by Django 6.0.4 on 2026-04-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('immunity', 'Immunity'), ('skin', 'Skin'), ('digestion', 'Digestion'), ('respiratory', 'Respiratory'), ('stress', 'Stress'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
