# Generated by Django 6.0.4 on 2026-06-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_plant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='ayurvedic_classification',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ayurvedic_importance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ayurvedic_properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='climate_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='contraindications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='cultural_relevance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='dosha_kapha',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='dosha_pitta',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='dosha_vata',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='flower_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='fruit_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='growth_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='hindi_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='historical_significance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='leaf_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='modern_uses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='native_region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='precautions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='recommended_usage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sanskrit_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='strength_anti_inflammatory',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='strength_digestive',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='strength_immunity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='strength_respiratory',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='telugu_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='traditional_uses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('immunity', 'Immunity Boosting Plants'), ('medicinal_herbs', 'Medicinal Herbs'), ('digestion', 'Digestive Health Plants'), ('respiratory', 'Respiratory Health Plants'), ('skin', 'Skin Care Plants'), ('hair', 'Hair Care Plants'), ('anti_inflammatory', 'Anti-inflammatory Plants'), ('stress', 'Stress Relief Plants'), ('trees', 'Ayurvedic Trees'), ('sacred', 'Sacred Plants'), ('kitchen', 'Kitchen Medicinal Herbs'), ('womens_health', "Women's Health Plants"), ('mens_health', "Men's Health Plants"), ('diabetes', 'Diabetes Support Plants'), ('heart', 'Heart Health Plants'), ('detox', 'Detoxifying Plants'), ('aromatic', 'Aromatic Medicinal Plants'), ('traditional', 'Traditional Indian Medicinal Plants'), ('rare', 'Rare Ayurvedic Plants')], default='medicinal_herbs', max_length=50),
        ),
    ]
