# Generated by Django 6.0.4 on 2026-06-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_plant_ayurvedic_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_user_added',
            field=models.BooleanField(default=False),
        ),
    ]
