import os
import django

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'herbal_garden.settings')
django.setup()

from garden.models import Plant

def seed_plants():
    # Only seed if database is empty
    if Plant.objects.exists():
        print("🌱 Database already has plant records. Skipping seeding to prevent overwriting existing or user-added data.")
        return

    print("🌱 Database is empty. Seeding default Ayurvedic plants...")
    plants_data = [
        {
            "name": "Tulsi (Holy Basil)",
            "scientific_name": "Ocimum tenuiflorum",
            "sanskrit_name": "Tulasi",
            "telugu_name": "Gagana / Tulasi",
            "hindi_name": "Tulsi",
            "family": "Lamiaceae",
            "native_region": "Indian Subcontinent",
            "uses": "Coughs, colds, fever, stress relief, respiratory support, and immune boosting.",
            "description": "Known as the 'Queen of Herbs', Tulsi is the most sacred plant in Hindu tradition and is revered for its strong medicinal properties. It is an adaptogen, helps manage stress, lowers temperature during fevers, and supports the respiratory system.",
            "category": "sacred",
            "ayurvedic_classification": "Rasayana (Rejuvenative), Tikta Rasa (Bitter taste), Kapha-Vata Hara",
            "ayurvedic_properties": "Rasa (Taste): Katu (Pungent), Tikta (Bitter); Guna (Physical Property): Laghu (Light), Ruksha (Dry); Virya (Potency): Ushna (Hot); Vipaka (Post-digestive effect): Katu",
            "traditional_uses": "Used traditionally for thousands of years in herbal tea infusions, juices, and powders to clear mucus from lungs, reduce fever, boost heart health, and promote longevity.",
            "modern_uses": "Used for its antioxidant, antimicrobial, anti-inflammatory, and stress-reducing properties. Active in modern organic cosmetics and stress supplements.",
            "dosha_vata": 30,  # Vata balancer (lowers Vata)
            "dosha_pitta": 70, # Increases Pitta in excess due to hot potency
            "dosha_kapha": 20, # Strongly pacifies Kapha
            "strength_immunity": 95,
            "strength_anti_inflammatory": 80,
            "strength_digestive": 75,
            "strength_respiratory": 98,
            "climate_requirements": "Tropical and subtropical climates. Warm temperatures with moderate rainfall.",
            "soil_requirements": "Rich loam or sandy soil with excellent drainage. pH levels between 6.0 and 7.5.",
            "water_requirements": "Regular watering. Keep soil moist but not waterlogged. Tolerates dry periods once established.",
            "sunlight_requirements": "Requires full sun to partial shade, at least 4-6 hours of daily sunlight.",
            "growth_conditions": "Can be easily grown in pots, gardens, and indoor planters. Sensitive to frost.",
            "precautions": "May lower blood glucose levels. Use caution if taking diabetic medications.",
            "side_effects": "Mild digestive warmness in highly sensitive Pitta constitutions if consumed in huge quantities.",
            "contraindications": "Avoid during pregnancy or if planning a pregnancy due to mild anti-fertility effects.",
            "recommended_usage": "Fresh leaf juice: 5-10 ml daily; Powder: 1-3 grams; Herbal Tea: 2-3 cups daily.",
            "historical_significance": "Revered in Vedic scriptures and planted in the courtyards of traditional Indian households for spiritual protection and air purification.",
            "ayurvedic_importance": "Considered a supreme adaptogen and a physical-spiritual cleanser that clears the auric field and expands mental clarity.",
            "cultural_relevance": "Worshipped as an incarnation of Goddess Lakshmi; vital in Hindu daily prayers and holy rituals."
        },
        {
            "name": "Neem",
            "scientific_name": "Azadirachta indica",
            "sanskrit_name": "Nimba",
            "telugu_name": "Vepa Chettu",
            "hindi_name": "Neem",
            "family": "Meliaceae",
            "native_region": "Tropical India and Myanmar",
            "uses": "Skin disorders, blood purification, dental hygiene, anti-fungal, and insect repellent.",
            "description": "Neem is a legendary tree known as the 'village pharmacy' in India. Every part of the tree—leaves, bark, seeds, and roots—is utilized for its powerful antibacterial, antifungal, anti-inflammatory, and purifying capabilities.",
            "category": "skin",
            "ayurvedic_classification": "Krimighna (Destroyer of worms/microbes), Kandughna (Relieves itching), Kushthaghna (Cures skin diseases)",
            "ayurvedic_properties": "Rasa (Taste): Tikta (Bitter), Kashaya (Astringent); Guna: Laghu, Ruksha; Virya: Sheeta (Cold); Vipaka: Katu",
            "traditional_uses": "Twigs used as natural toothbrushes; leaf paste applied to wounds, acne, and chickenpox rashes; leaf decoction used to purify blood and clean infections.",
            "modern_uses": "Used globally in organic soaps, acne creams, toothpaste, shampoos, and organic bio-pesticides.",
            "dosha_vata": 85,  # Can increase Vata due to extreme cold/dry nature
            "dosha_pitta": 15, # Extremely effective in balancing Pitta (heat, inflammation)
            "dosha_kapha": 25, # Excellent for reducing Kapha (oiliness, congestion)
            "strength_immunity": 88,
            "strength_anti_inflammatory": 92,
            "strength_digestive": 70,
            "strength_respiratory": 60,
            "climate_requirements": "Dry, hot, tropical climates. Drought-resistant and cannot tolerate freezing temperatures.",
            "soil_requirements": "Grows in almost all soils including clayey, saline, and stony soils. Needs good drainage.",
            "water_requirements": "Low water requirements. Once rooted, it survives on minimal rainfall.",
            "sunlight_requirements": "Thrives in full blazing sunlight. Not suitable for deep shade.",
            "growth_conditions": "Fast-growing evergreen tree that can reach heights of 15-20 meters. Ideal shade tree.",
            "precautions": "Extremely bitter taste. Avoid overconsumption as it can cause fatigue or affect liver in high dose.",
            "side_effects": "Can lower blood pressure or glucose, leading to lightheadedness if taken excessively on empty stomach.",
            "contraindications": "Strictly contraindicated for infants, pregnant women, and couples trying to conceive.",
            "recommended_usage": "Leaf paste for skin: apply locally; Leaf decoction: 10-20 ml; Dental twigs: chew daily.",
            "historical_significance": "Mentioned in the Atharva Veda as a healer of all diseases and a gift of celestial nectar dropped from heaven.",
            "ayurvedic_importance": "The ultimate blood purifier (Rakta Shodhana) and cooling agent for inflammatory skin conditions.",
            "cultural_relevance": "Leaves are eaten during Hindu New Year (Ugadi/Gudi Padwa) to symbolize welcoming both the bitter and sweet aspects of life."
        },
        {
            "name": "Ashwagandha",
            "scientific_name": "Withania somnifera",
            "sanskrit_name": "Ashwagandha",
            "telugu_name": "Penneru / Ashwagandha",
            "hindi_name": "Ashwagandha",
            "family": "Solanaceae",
            "native_region": "Dry parts of India, Middle East, and Africa",
            "uses": "Stress relief, anxiety reduction, physical strength, stamina, and nervous system support.",
            "description": "Ashwagandha, often called 'Indian Ginseng', is the premier adaptogenic herb in Ayurveda. Its name means 'smell of a horse', referring to both its unique root aroma and its traditional reputation for giving the strength and vitality of a stallion.",
            "category": "stress",
            "ayurvedic_classification": "Balya (Strength promoter), Rasayana (Rejuvenative), Vajikarana (Aphrodisiac)",
            "ayurvedic_properties": "Rasa (Taste): Tikta (Bitter), Katu (Pungent), Madhura (Sweet); Guna: Laghu, Snigdha (Unctuous); Virya: Ushna (Hot); Vipaka: Madhura",
            "traditional_uses": "Root powder mixed with warm milk and honey is taken before bedtime to promote deep sleep, restore vigor, calm the nerves, and boost muscles.",
            "modern_uses": "Extensively studied and sold as a dietary supplement for lowering cortisol levels, combating fatigue, improving sleep quality, and enhancing athletic performance.",
            "dosha_vata": 15,  # Greatly balances Vata (nourishes nervous system)
            "dosha_pitta": 65, # Can elevate Pitta in excess due to its hot potency
            "dosha_kapha": 25, # Balances Kapha due to light and dry qualities
            "strength_immunity": 94,
            "strength_anti_inflammatory": 85,
            "strength_digestive": 60,
            "strength_respiratory": 65,
            "climate_requirements": "Arid to semi-arid regions. Needs dry conditions with moderate warm temperature.",
            "soil_requirements": "Well-drained, sandy-loam or light red soils. Susceptible to root rot if soil retains water.",
            "water_requirements": "Very low water needs. Drought tolerant once established; water only when soil is bone dry.",
            "sunlight_requirements": "Requires full, direct sunlight.",
            "growth_conditions": "Short woody shrub growing up to 1.5 meters. Roots are harvested in dry winter seasons.",
            "precautions": "May cause mild drowsiness. Should not be taken with chemical sedatives.",
            "side_effects": "Excessive doses may cause stomach upset or mild body heat.",
            "contraindications": "Avoid during pregnancy (acts as an abortifacient in large quantities) and active autoimmune diseases.",
            "recommended_usage": "Root powder: 3-5 grams twice daily with milk/water; Extract capsule: 300-500 mg daily.",
            "historical_significance": "A fundamental element of traditional Ayurvedic formulas (like Chyawanprash) documented in Charaka Samhita 3000 years ago.",
            "ayurvedic_importance": "The ultimate nervous system rejuvenator (Majja Dhatu Rasayana) that nourishes tissues and improves sleep.",
            "cultural_relevance": "Symbolizes vitality, resilience, and calm, steady strength in Indian folk culture."
        },
        {
            "name": "Amla (Indian Gooseberry)",
            "scientific_name": "Phyllanthus emblica",
            "sanskrit_name": "Amalaki",
            "telugu_name": "Usiri Kaya",
            "hindi_name": "Amla",
            "family": "Phyllanthaceae",
            "native_region": "Tropical India and Southeast Asia",
            "uses": "Immunity booster, hair health, digestion support, anti-aging, and rich Vitamin C source.",
            "description": "Amla is a medium-sized deciduous tree famous for its sour, highly nutritious green fruits. It contains one of the highest concentrations of stable Vitamin C in the plant kingdom and is considered a prime longevity herb in Ayurveda.",
            "category": "immunity",
            "ayurvedic_classification": "Tridosha Hara (Balances all 3 Doshas), Vayasthapana (Anti-aging), Chakshushya (Good for eyes)",
            "ayurvedic_properties": "Rasa (Taste): Has 5 tastes except salty, predominantly Amla (Sour) and Kashaya (Astringent); Guna: Guru (Heavy), Sheeta; Virya: Sheeta (Cold); Vipaka: Madhura",
            "traditional_uses": "Used to make 'Amla Murabba' (sweet preserve), hair oils to prevent graying, and as the main ingredient in Triphala and Chyawanprash for internal strength.",
            "modern_uses": "Used in natural Vitamin C tablets, hair serums, digestive powders, and organic anti-aging skin care formulations.",
            "dosha_vata": 25,  # Pacifies Vata due to sweet and sour taste
            "dosha_pitta": 15, # Superb for pacifying Pitta due to cold potency and sweet post-digestive effect
            "dosha_kapha": 30, # Pacifies Kapha due to dry and astringent tastes
            "strength_immunity": 99,
            "strength_anti_inflammatory": 86,
            "strength_digestive": 90,
            "strength_respiratory": 80,
            "climate_requirements": "Warm, sunny climates. Avoids areas with heavy frost or extreme cold wind.",
            "soil_requirements": "Loamy, well-drained soils. Can tolerate alkaline and slightly saline soils.",
            "water_requirements": "Moderate watering. Requires watering during dry fruit development seasons.",
            "sunlight_requirements": "Thrives in full sun.",
            "growth_conditions": "Deciduous tree growing up to 8 meters. Fruits mature in late autumn/winter.",
            "precautions": "Astringent action may cause dryness in bowels if taken in high dry powder format without water.",
            "side_effects": "Excessive sourness may cause mild dental sensitivity or throat tickle.",
            "contraindications": "None significant. Safe for long term consumption.",
            "recommended_usage": "Fresh juice: 10-20 ml; Dry fruit powder: 3-6 grams; Chyawanprash: 1 teaspoon daily.",
            "historical_significance": "Revered in Hindu myth as the first tree to grow on Earth, arising from the tears of Lord Brahma.",
            "ayurvedic_importance": "Unique because most sour things increase Pitta, but Amla cools Pitta and boosts digestive fire (Agni) without overheating.",
            "cultural_relevance": "Worshipped during 'Amalaki Ekadashi' and 'Akshaya Navami', where families eat meals under the tree for health."
        },
        {
            "name": "Giloy (Guduchi)",
            "scientific_name": "Tinospora cordifolia",
            "sanskrit_name": "Guduchi / Amrita",
            "telugu_name": "Tippa Teega",
            "hindi_name": "Giloy",
            "family": "Menispermaceae",
            "native_region": "Tropical India, Sri Lanka, and Bangladesh",
            "uses": "Immunity booster, chronic fevers, detoxification, arthritis relief, and liver support.",
            "description": "Giloy is known as 'Amrita' (the root of immortality) due to its incredible rejuvenating qualities. It is a large, climbing deciduous shrub with heart-shaped leaves and long aerial roots.",
            "category": "detox",
            "ayurvedic_classification": "Jvarahara (Fever reducer), Vayasthapana (Rejuvenative), Dahaprashamana (Burning sensation reliever)",
            "ayurvedic_properties": "Rasa (Taste): Tikta (Bitter), Kashaya (Astringent); Guna: Laghu, Snigdha; Virya: Ushna (Hot); Vipaka: Madhura",
            "traditional_uses": "Stem decoction taken daily to combat chronic fevers like Dengue and Malaria, increase blood platelets, clear toxins from the liver, and soothe joint pain.",
            "modern_uses": "Used in immune support supplements, anti-gout capsules, liver tonics, and respiratory tablets.",
            "dosha_vata": 20,  # Highly balances Vata (snigdha / sweet vipaka)
            "dosha_pitta": 25, # Excellent Pitta balancer despite hot virya due to sweet post-digestive effect
            "dosha_kapha": 20, # Strongly balances Kapha due to bitter taste
            "strength_immunity": 98,
            "strength_anti_inflammatory": 90,
            "strength_digestive": 85,
            "strength_respiratory": 88,
            "climate_requirements": "Tropical climate with warm, humid conditions. Grows well throughout India.",
            "soil_requirements": "Requires well-drained, sandy-loam soils rich in organic matter.",
            "water_requirements": "Moderate water. Can survive dry spells but grows faster with moderate watering.",
            "sunlight_requirements": "Prefers partial shade to full sun. Needs support like a trellis or adjacent tree.",
            "growth_conditions": "Fast growing climber. High medicinal value is attributed to Giloy climbing on a Neem tree ('Neem Giloy').",
            "precautions": "May lower blood sugar. Monitor closely if on diabetes medication.",
            "side_effects": "Rare. Might cause mild constipation in very high doses.",
            "contraindications": "Avoid if suffering from active autoimmune conditions without practitioner guidance.",
            "recommended_usage": "Stem juice: 10-20 ml; Stem decoction (Kadha): 30-50 ml; Powder: 1-3 grams.",
            "historical_significance": "According to Ramayana, when Lord Rama prayed for his fallen monkey warriors, drops of Amrit fell from heaven and grew into Giloy.",
            "ayurvedic_importance": "One of the rare herbs that is both bitter (detoxifying) and rejuvenative (nourishing) at the same time.",
            "cultural_relevance": "Became highly popular in modern Indian households during the COVID-19 pandemic as a natural immunity booster."
        },
        {
            "name": "Aloe Vera",
            "scientific_name": "Aloe barbadensis",
            "sanskrit_name": "Kumari",
            "telugu_name": "Kalabanda",
            "hindi_name": "Ghee Kanwar / Aloe Vera",
            "family": "Asphodelaceae",
            "native_region": "Arabian Peninsula, naturalized worldwide",
            "uses": "Skin healing, digestion, liver detox, burn relief, and hair conditioning.",
            "description": "Aloe Vera is a succulent plant species containing a clear soothing gel inside its thick green leaves. It has been used for centuries globally for skincare, digestive soothing, and metabolic regulation.",
            "category": "hair",
            "ayurvedic_classification": "Bhedana (Purgative), Rasayana (Rejuvenative), Balya (Strengthening)",
            "ayurvedic_properties": "Rasa (Taste): Tikta, Madhura (Sweet); Guna: Guru (Heavy), Snigdha, Picchila (Slimy); Virya: Sheeta (Cold); Vipaka: Madhura",
            "traditional_uses": "Gel applied directly to sun burns, wounds, and dry scalp; leaf skin extract taken orally as a strong laxative; juice taken for acid reflux and stomach ulcers.",
            "modern_uses": "Pervasive ingredient in cosmetics, sunburn lotions, face washes, moisturizers, health juices, and hair masks.",
            "dosha_vata": 40,  # Balances Vata due to sweet taste and unctuous nature
            "dosha_pitta": 10, # Superbly pacifies Pitta due to cold potency and soothing nature
            "dosha_kapha": 60, # Can increase Kapha slightly in excess due to heavy, slimy nature
            "strength_immunity": 80,
            "strength_anti_inflammatory": 88,
            "strength_digestive": 85,
            "strength_respiratory": 50,
            "climate_requirements": "Warm, sunny, dry climates. Highly sensitive to frost and freezing conditions.",
            "soil_requirements": "Porous, sandy, well-draining soil. Succulent soil mix is ideal.",
            "water_requirements": "Very low water. Water deeply but let soil dry out completely between watering.",
            "sunlight_requirements": "Thrives in bright, indirect or direct morning sunlight.",
            "growth_conditions": "Easy to grow indoors or outdoors. Produces offsets ('pups') rapidly.",
            "precautions": "Outer leaf skin contains aloin, which is a powerful laxative and should be washed off before consuming inner gel.",
            "side_effects": "Eating too much aloin can cause severe abdominal cramping and electrolyte imbalance.",
            "contraindications": "Not recommended during pregnancy (may cause uterine contractions) or for kidney disease sufferers.",
            "recommended_usage": "Fresh inner leaf gel: 2-3 tablespoons; Pure juice: 15-30 ml daily.",
            "historical_significance": "Ancient Egyptians called it the 'plant of immortality' and Cleopatra used it as part of her beauty regime.",
            "ayurvedic_importance": "Referred to as 'Kumari' (meaning young maiden), symbolizing its ability to restore youthfulness, regulate menstruation, and beautify skin.",
            "cultural_relevance": "Frequently placed at the entrances of Indian homes to ward off negative energy and bring fresh oxygen."
        },
        {
            "name": "Brahmi",
            "scientific_name": "Bacopa monnieri",
            "sanskrit_name": "Brahmi / Sarasvati",
            "telugu_name": "Brahmi / Saraswathi Aku",
            "hindi_name": "Brahmi",
            "family": "Plantaginaceae",
            "native_region": "Wetlands of India, East Asia, and America",
            "uses": "Memory enhancement, concentration, stress reduction, cognitive support, and hair growth.",
            "description": "Brahmi is a small, creeping perennial herb that grows in marshy areas. It is the chief brain tonic in Ayurvedic science, famous for boosting memory, intellectual power, concentration, and calming the central nervous system.",
            "category": "stress",
            "ayurvedic_classification": "Medhya (Brain tonic), Ayushya (Longevity promoter), Prajasthapana (Promotes fertility)",
            "ayurvedic_properties": "Rasa (Taste): Tikta, Kashaya; Guna: Laghu; Virya: Sheeta; Vipaka: Madhura",
            "traditional_uses": "Fresh juice administered to children for memory and speech development; leaf powder infused in sesame or coconut oil ('Brahmi Amla Oil') to massage the head for stress relief.",
            "modern_uses": "Active in brain health supplements, ADHD support formulations, hair fall prevention oils, and memory enhancement drinks.",
            "dosha_vata": 20,  # Balances Vata (calms nervous anxiety)
            "dosha_pitta": 15, # Highly cools Pitta (reduces mental anger and heat)
            "dosha_kapha": 25, # Clears Kapha stagnation in the brain (combats lethargy)
            "strength_immunity": 75,
            "strength_anti_inflammatory": 82,
            "strength_digestive": 60,
            "strength_respiratory": 65,
            "climate_requirements": "Warm, humid, wet climates. Grows best near streams or marshy water sources.",
            "soil_requirements": "Clayey or loamy soils that retain moisture. Can even grow in water logged mud.",
            "water_requirements": "High water. Soil must remain continuously wet; can be submerged in water gardens.",
            "sunlight_requirements": "Partial shade to full sun. Needs protection from extreme dry heat.",
            "growth_conditions": "Low creeping growth. Excellent for terrariums, moist margins of garden ponds, and pots.",
            "precautions": "May cause mild nausea or dry mouth if taken in high dose on empty stomach.",
            "side_effects": "Slight increase in thyroid hormones reported in rare animal studies.",
            "contraindications": "Use caution if taking thyroid hormones, or suffering from bradycardia (slow heart rate).",
            "recommended_usage": "Fresh juice: 5-10 ml; Dry leaf powder: 2-3 grams; Brahmi Ghee: 1 teaspoon.",
            "historical_significance": "Named after Lord Brahma (the creator God) or Brahmam (cosmic consciousness) due to its power to awaken higher intellect.",
            "ayurvedic_importance": "The ultimate 'Medhya Rasayana' that balances both cerebral activity and emotional stability.",
            "cultural_relevance": "Symbolizes intelligence, wisdom, and cosmic truth; historically eaten by scholars before studying."
        },
        {
            "name": "Shatavari",
            "scientific_name": "Asparagus racemosus",
            "sanskrit_name": "Shatavari",
            "telugu_name": "Pilli Teegalu / Shatavari",
            "hindi_name": "Shatavari",
            "family": "Asparagaceae",
            "native_region": "India, Sri Lanka, and parts of Africa",
            "uses": "Women's health, hormonal balance, lactation support, strength, and reproductive tonic.",
            "description": "Shatavari is a species of wild asparagus with climbing, thorny stems and tuberous roots. Its name translates to 'she who possesses a hundred husbands', referring to its traditional use as a highly nourishing rejuvenative tonic for female reproductive health and fertility.",
            "category": "womens_health",
            "ayurvedic_classification": "Rasayana (Rejuvenative), Stanyajanana (Promotes breast milk), Balya (Nourishing)",
            "ayurvedic_properties": "Rasa (Taste): Madhura, Tikta; Guna: Guru, Snigdha; Virya: Sheeta; Vipaka: Madhura",
            "traditional_uses": "Tuberous root powder boiled in milk is given to lactating mothers to increase milk production and to women of all ages to balance hormones and regulate cycles.",
            "modern_uses": "Used in women's wellness tea, menopause support capsules, hormonal balance supplements, and general vitality powders.",
            "dosha_vata": 20,  # Balances Vata (grounds and nourishes dry tissues)
            "dosha_pitta": 15, # Strongly cools Pitta (soothes acidity and hot flashes)
            "dosha_kapha": 70, # May increase Kapha in excess due to heavy and oily nature
            "strength_immunity": 85,
            "strength_anti_inflammatory": 80,
            "strength_digestive": 78,
            "strength_respiratory": 60,
            "climate_requirements": "Subtropical to tropical climates. Drought-tolerant but sensitive to frost.",
            "soil_requirements": "Sandy-loam, loose, rocky or well-drained soils that allow tuber roots to expand.",
            "water_requirements": "Moderate water. Tuberous roots store water, making the plant drought resistant.",
            "sunlight_requirements": "Prefers partial shade or indirect bright sunlight.",
            "growth_conditions": "Woody climber with needle-like cladodes (leaves). Roots require 1-2 years to mature for harvest.",
            "precautions": "Avoid if you have a tendency to retain water or suffer from congestion due to high Kapha.",
            "side_effects": "Weight gain may occur in Kapha dominant individuals due to high nutritive nature.",
            "contraindications": "Contraindicated in estrogen-sensitive disorders or severe fibroids without physician consultation.",
            "recommended_usage": "Root powder: 3-6 grams daily with warm milk; Shatavari Ghee: 1-2 teaspoons.",
            "historical_significance": "Described in Ayurveda texts as 'the friend of women' due to its supportive nature across puberty, motherhood, and menopause.",
            "ayurvedic_importance": "Crucial for strengthening Ojas (vital energy force) and nourishing Shukra Dhatu (reproductive fluids).",
            "cultural_relevance": "Symbolizes motherly nutrition, fertility, and soft resilience in traditional Indian medical lore."
        },
        {
            "name": "Turmeric",
            "scientific_name": "Curcuma longa",
            "sanskrit_name": "Haridra / Kanchani",
            "telugu_name": "Pasupu",
            "hindi_name": "Haldi",
            "family": "Zingiberaceae",
            "native_region": "Indian Subcontinent and Southeast Asia",
            "uses": "Anti-inflammatory, wound healing, joint health, skin glowing, and natural antiseptic.",
            "description": "Turmeric is a perennial herbaceous plant of the ginger family. Its underground stems (rhizomes) contain curcumin, a powerful golden pigment famous for its anti-inflammatory, antioxidant, and tissue healing properties.",
            "category": "anti_inflammatory",
            "ayurvedic_classification": "Lekhana (Scraping toxins/cholesterol), Varnya (Improves complexion), Vishaghna (Antidote to poisons)",
            "ayurvedic_properties": "Rasa (Taste): Tikta, Katu; Guna: Ruksha, Laghu; Virya: Ushna; Vipaka: Katu",
            "traditional_uses": "Golden Milk ('Haldi Doodh') drank for cold/cough and physical pain; paste applied to cuts, burns, acne, and used during wedding purification rituals.",
            "modern_uses": "Globally used as curcumin supplements for joint arthritis, herbal anti-inflammatory teas, turmeric lattes, and skincare creams.",
            "dosha_vata": 40,  # Balances Vata in moderation (warmth settles spasm)
            "dosha_pitta": 50, # Increases Pitta slightly if overused due to hot potency
            "dosha_kapha": 15, # Strongly pacifies Kapha (dries excess oil/mucus)
            "strength_immunity": 96,
            "strength_anti_inflammatory": 99,
            "strength_digestive": 82,
            "strength_respiratory": 88,
            "climate_requirements": "Warm and humid climates. Requires temperatures between 20°C and 30°C.",
            "soil_requirements": "Well-drained, sandy-loam, gravelly soils rich in humus.",
            "water_requirements": "Requires regular watering. Crop takes 7-9 months to mature and needs consistent moisture.",
            "sunlight_requirements": "Partial shade to full sun. Needs warmth to grow healthy rhizomes.",
            "growth_conditions": "Propagated via small seed rhizomes. Leaves grow large and green, smelling aromatic.",
            "precautions": "High doses may irritate stomach or thin the blood. Always consume with a pinch of black pepper to increase absorption.",
            "side_effects": "Excessive intake might cause body heat or mild heartburn in highly hot climates.",
            "contraindications": "Avoid therapeutic doses before surgeries or if suffering from bile duct blockage/gallstones.",
            "recommended_usage": "Fresh rhizome juice: 5-10 ml; Powder: 1-3 grams; Golden Milk: 1 cup at night.",
            "historical_significance": "An integral part of Indian cooking, traditional medicine, and ancient textiles (as a natural yellow dye) for 4000+ years.",
            "ayurvedic_importance": "Purifies the blood (Rakta Shodhana) and promotes circulation, flexibility, and strong immunity.",
            "cultural_relevance": "Sacred yellow color symbol of fertility and prosperity; used in all Hindu spiritual ceremonies and marriage rituals."
        },
        {
            "name": "Moringa",
            "scientific_name": "Moringa oleifera",
            "sanskrit_name": "Shigru",
            "telugu_name": "Munaga Chettu",
            "hindi_name": "Sahjan / Moringa",
            "family": "Moringaceae",
            "native_region": "Northwestern India (Himalayan foothills)",
            "uses": "Nutritional supplement, joint pain relief, blood sugar regulation, and energy booster.",
            "description": "Commonly known as the 'Drumstick Tree' or 'Miracle Tree', Moringa is a fast-growing deciduous tree. Its leaves are packed with amino acids, calcium, iron, potassium, and vitamins, serving as a highly potent natural multivitamin.",
            "category": "immunity",
            "ayurvedic_classification": "Deepana (Appetizer), Shothahara (Anti-inflammatory), Krimighna (Antiparasitic)",
            "ayurvedic_properties": "Rasa (Taste): Katu, Tikta; Guna: Laghu, Ruksha, Tikshna (Sharp); Virya: Ushna; Vipaka: Katu",
            "traditional_uses": "Moringa pods (drumsticks) used in sambar soup; leaf decoction given for joint pains, arthritis, and swelling; root paste applied externally to relieve pain.",
            "modern_uses": "Sold globally as green leaf powders, nutritional capsules, energy bars, and moringa seed oil in cosmetics.",
            "dosha_vata": 25,  # Balances Vata due to warm and grounding properties
            "dosha_pitta": 60, # May increase Pitta due to sharp and hot properties
            "dosha_kapha": 20, # Strongly balances Kapha (scrapes fat and mucus)
            "strength_immunity": 92,
            "strength_anti_inflammatory": 88,
            "strength_digestive": 84,
            "strength_respiratory": 70,
            "climate_requirements": "Subtropical and tropical arid areas. Highly drought tolerant.",
            "soil_requirements": "Thrives in poor sandy or loamy soils. Extremely sensitive to waterlogged soils.",
            "water_requirements": "Very low. Water young plants; established trees survive on rainfall alone.",
            "sunlight_requirements": "Requires full, direct hot sun. Grow poorly in shade.",
            "growth_conditions": "Grows very fast, up to 10-12 meters. Easily propagated from cuttings or seeds.",
            "precautions": "Do not consume root bark, as it contains toxic alkaloids. Stick to leaves and pods.",
            "side_effects": "High quantities of raw leaves might cause digestive laxity or warm feeling in stomach.",
            "contraindications": "Avoid taking concentrated leaf extracts during pregnancy.",
            "recommended_usage": "Dry leaf powder: 1 teaspoon (3-5 grams); Fresh leaves in cooking: 1/2 cup daily.",
            "historical_significance": "Ancient Indian warriors were fed moringa extracts on battlefields to give them strength and relieve joint soreness.",
            "ayurvedic_importance": "Valued for its 'Tikshna' (sharp and penetrating) quality, which helps herbs penetrate deep into joint tissues to clear toxins (Amavisha).",
            "cultural_relevance": "An essential culinary herb in South Indian homes, praised for both its taste and immediate health benefits."
        },
        {
            "name": "Curry Leaves",
            "scientific_name": "Murraya koenigii",
            "sanskrit_name": "Kaaraveera / Karipatta",
            "telugu_name": "Karivepaku",
            "hindi_name": "Kadi Patta",
            "family": "Rutaceae",
            "native_region": "India and Sri Lanka",
            "uses": "Digestion improvement, hair growth, eye health, diabetes control, and cholesterol management.",
            "description": "Curry leaves are highly aromatic small leaves from a tropical tree. Widely used in Indian culinary dishes, they are valued in Ayurveda for improving digestion, promoting lush black hair, and managing blood glucose.",
            "category": "kitchen",
            "ayurvedic_classification": "Chakshushya (Good for eyes), Kesha Ranjana (Darkens and strengthens hair), Deepana-Pachana (Appetizer-Digestive)",
            "ayurvedic_properties": "Rasa (Taste): Kashaya (Astringent), Tikta, Madhura; Guna: Laghu, Snigdha; Virya: Sheeta (Cold); Vipaka: Katu",
            "traditional_uses": "Leaves fried in coconut oil to make hair oil; fresh leaves chewed on empty stomach for weight management and diabetes; paste mixed with buttermilk for diarrhea.",
            "modern_uses": "Used in botanical hair growth oils, organic food spices, anti-diabetic herbal formulations, and antioxidant face serums.",
            "dosha_vata": 40,  # Balances Vata in moderation
            "dosha_pitta": 15, # Strongly balances Pitta due to cooling and sweet qualities
            "dosha_kapha": 25, # Pacifies Kapha due to bitter/astringent tastes
            "strength_immunity": 80,
            "strength_anti_inflammatory": 75,
            "strength_digestive": 92,
            "strength_respiratory": 45,
            "climate_requirements": "Warm, sunny, humid climates. Sensitive to severe frost.",
            "soil_requirements": "Rich, well-drained loamy soils. Thrives in organic compost.",
            "water_requirements": "Moderate water. Let the topsoil dry out slightly between waterings.",
            "sunlight_requirements": "Prefers full sun to partial afternoon shade.",
            "growth_conditions": "Small shrubby tree growing up to 4-5 meters. Can be easily grown in home gardens or pots.",
            "precautions": "Consume fresh. Avoid eating the dark purple seeds as they are toxic.",
            "side_effects": "None in culinary doses. Safe for everyone.",
            "contraindications": "None.",
            "recommended_usage": "Fresh leaves: 5-10 chewed raw daily; Hair oil: massage scalp 2-3 times weekly.",
            "historical_significance": "Mentioned in ancient Tamil literature (like 'Agananuru') dating back to the Sangam period for its culinary and therapeutic use.",
            "ayurvedic_importance": "Acts as a mild 'Pachana' (digestive toxin burner) that cleanses blood and strengthens hair roots.",
            "cultural_relevance": "An absolute staple in Indian cooking; no tempering (tadka) of dishes is complete without fresh curry leaves."
        },
        {
            "name": "Hibiscus",
            "scientific_name": "Hibiscus rosa-sinensis",
            "sanskrit_name": "Japa / Jaba",
            "telugu_name": "Mandara Puvvu",
            "hindi_name": "Gudhal",
            "family": "Malvaceae",
            "native_region": "Tropical Asia",
            "uses": "Hair fall control, blood pressure control, cooling, and kidney care.",
            "description": "Hibiscus is a popular evergreen flowering shrub with showy, bright red flowers. In Ayurveda, it is highly cooling and is used extensively for hair growth, dandruff reduction, blood purification, and cardiovascular cooling.",
            "category": "hair",
            "ayurvedic_classification": "Keshya (Promotes hair growth), Rakta-Stambhana (Stops bleeding/cools blood), Mootrala (Diuretic)",
            "ayurvedic_properties": "Rasa (Taste): Kashaya, Madhura; Guna: Laghu, Ruksha; Virya: Sheeta; Vipaka: Katu",
            "traditional_uses": "Petals and leaves ground into shampoo paste; flower tea consumed to lower blood pressure and cool body heat during summers; oil infusion used to combat baldness.",
            "modern_uses": "Used in commercial herbal shampoos, organic red teas, anti-hypertensive supplements, and natural hair dyes.",
            "dosha_vata": 65,  # Can increase Vata slightly due to dry properties
            "dosha_pitta": 10, # Superbly balances Pitta (cools heart and liver)
            "dosha_kapha": 25, # Balances Kapha due to drying nature
            "strength_immunity": 78,
            "strength_anti_inflammatory": 82,
            "strength_digestive": 50,
            "strength_respiratory": 60,
            "climate_requirements": "Warm, sunny, frost-free tropical and subtropical climates.",
            "soil_requirements": "Well-drained, organic soils. Prefers slightly acidic soil conditions.",
            "water_requirements": "Requires regular watering. Water whenever the top 2 inches of soil feels dry.",
            "sunlight_requirements": "Thrives in full sun (at least 6 hours of bright light daily) for abundant blooming.",
            "growth_conditions": "Medium shrub growing up to 3-4 meters. Prune regularly to maintain shape and blooms.",
            "precautions": "Mildly diuretic. Do not drink in massive excess if taking prescription water pills.",
            "side_effects": "None known in standard dosage.",
            "contraindications": "Avoid in extremely low blood pressure states unless supervised.",
            "recommended_usage": "Flower tea: 1-2 cups daily; Hair paste: apply to scalp for 30 minutes before washing.",
            "historical_significance": "Historically offered to Goddess Kali and Lord Ganesha in Hindu tradition, representing intense devotion and vital energy.",
            "ayurvedic_importance": "Cools the physical and mental heart (Sadhaka Pitta), reducing irritability, anger, and hot flashes.",
            "cultural_relevance": "Red hibiscus flowers are a common garden sight across India, used for both cosmetic and worship needs."
        },
        {
            "name": "Mint",
            "scientific_name": "Mentha arvensis",
            "sanskrit_name": "Pudina",
            "telugu_name": "Pudina",
            "hindi_name": "Pudina",
            "family": "Lamiaceae",
            "native_region": "Temperate regions of Europe and Asia",
            "uses": "Indigestion relief, gas/bloating, breath freshening, and respiratory cooling.",
            "description": "Mint is a fast-spreading herbaceous plant with refreshing green leaves containing menthol. It is widely praised for its cooling taste, quick digestive action, and clearing nasal passages.",
            "category": "kitchen",
            "ayurvedic_classification": "Rochana (Improves taste), Deepana (Appetizer), Kasahara (Relieves cough)",
            "ayurvedic_properties": "Rasa (Taste): Katu (Pungent); Guna: Laghu, Ruksha, Tikshna; Virya: Ushna (Warm initially, cooling effect post-digestion); Vipaka: Katu",
            "traditional_uses": "Mint chutney eaten for digestion; leaf tea drunk for stomach cramps, gas, and nausea; crushed leaves applied to temples for headaches.",
            "modern_uses": "Key ingredient in toothpastes, chewing gums, digestive tablets, pain balms, and refreshing summer drinks.",
            "dosha_vata": 30,  # Balances Vata (calms muscle spasm and gas)
            "dosha_pitta": 25, # Balances Pitta due to its refreshing, cooling post-effect
            "dosha_kapha": 20, # Reduces Kapha mucus and lethargy
            "strength_immunity": 70,
            "strength_anti_inflammatory": 76,
            "strength_digestive": 95,
            "strength_respiratory": 85,
            "climate_requirements": "Cooler climates but grows easily in tropical areas if shaded during hot afternoons.",
            "soil_requirements": "Rich, moist, organic soil with good moisture retention.",
            "water_requirements": "Requires frequent watering. Soil should remain consistently moist.",
            "sunlight_requirements": "Partial shade is best. Tends to dry up in scorching midday sun.",
            "growth_conditions": "Highly invasive root system (runners). Grow in pots to prevent it from overtaking garden beds.",
            "precautions": "Excessive consumption may cause acid reflux in highly sensitive individuals.",
            "side_effects": "None in culinary doses.",
            "contraindications": "Severe gastroesophageal reflux disease (GERD) sufferers should limit intake as menthol relaxes the esophageal sphincter.",
            "recommended_usage": "Fresh leaf juice: 5-10 ml; Mint tea: 1-2 cups daily; Fresh leaves in cooking.",
            "historical_significance": "Used in Greek, Roman, and Ayurvedic medicine since antiquity for purifying water and soothing irritable bowels.",
            "ayurvedic_importance": "Improves taste perception (Ruchi) and sparks the appetite (Agni) without creating high internal heat.",
            "cultural_relevance": "Used in traditional refreshing street food waters (Pani Puri) and chutneys throughout India."
        },
        {
            "name": "Lemongrass",
            "scientific_name": "Cymbopogon citratus",
            "sanskrit_name": "Bhustrina",
            "telugu_name": "Nimmagaddi",
            "hindi_name": "Lemongrass",
            "family": "Poaceae",
            "native_region": "Maritime Southeast Asia and India",
            "uses": "Fever, cold relief, detox, joint pain, and digestive health.",
            "description": "Lemongrass is a tall, perennial grass with a strong citrusy aroma. It contains essential oils like citral, making it highly valuable for detoxifying teas, lowering fevers, and calming muscle aches.",
            "category": "aromatic",
            "ayurvedic_classification": "Svedajana (Induces sweating/fever relief), Deepana (Appetizer), Krimighna (Antimicrobial)",
            "ayurvedic_properties": "Rasa (Taste): Katu, Tikta; Guna: Laghu, Ruksha, Tikshna; Virya: Ushna (Warm); Vipaka: Katu",
            "traditional_uses": "Stalks boiled in water with ginger for cold and flu relief; essential oil mixed with carrier oil for massage on arthritic joints.",
            "modern_uses": "Used in herbal teas, soaps, aromatherapy oils, mosquito repellents, and Asian cuisines.",
            "dosha_vata": 30,  # Balances Vata (warmth relieves spasms)
            "dosha_pitta": 75, # Can increase Pitta if taken in large quantities due to heating nature
            "dosha_kapha": 20, # Greatly pacifies Kapha (dries dampness)
            "strength_immunity": 82,
            "strength_anti_inflammatory": 80,
            "strength_digestive": 86,
            "strength_respiratory": 90,
            "climate_requirements": "Warm, humid climates with plenty of rainfall. Sensitive to freezing.",
            "soil_requirements": "Sandy, loamy, well-draining soil. pH of 5.5 to 7.5.",
            "water_requirements": "Moderate watering. Tolerates drought once established.",
            "sunlight_requirements": "Requires full sun.",
            "growth_conditions": "Clump-forming grass growing up to 1.5 meters. Propagated by dividing root clumps.",
            "precautions": "Essential oil should never be consumed directly and must be diluted for skin application.",
            "side_effects": "Skin irritation if applied undiluted.",
            "contraindications": "Do not take lemongrass oil internally during pregnancy.",
            "recommended_usage": "Lemongrass tea: 1-2 cups daily using 1 stalk; Diluted oil for skin: 2-3 drops in carrier oil.",
            "historical_significance": "Known historically as 'fever grass' in folk cultures due to its immediate capacity to induce sweating and break fevers.",
            "ayurvedic_importance": "Valued for its capacity to scrape toxins (Lekhana) from channels and clear respiratory blockages.",
            "cultural_relevance": "An essential element of wellness spas and soothing herbal teas."
        },
        {
            "name": "Bael",
            "scientific_name": "Aegle marmelos",
            "sanskrit_name": "Bilva / Sriphala",
            "telugu_name": "Maredu",
            "hindi_name": "Bel",
            "family": "Rutaceae",
            "native_region": "Indian Subcontinent and Indochina",
            "uses": "Diarrhea, dysentery, digestive disorders, diabetes, and cooling stomach.",
            "description": "Bael is a sacred deciduous tree bearing hard-shelled fruits with a sweet, aromatic pulp. In Ayurveda, unripe Bael is the premier remedy for loose stools and IBS, while ripe Bael cools the stomach and acts as a laxative.",
            "category": "trees",
            "ayurvedic_classification": "Grahi (Absorbent of liquid stools), Sangrahi (Digestive binder), Deepana (Appetizer)",
            "ayurvedic_properties": "Rasa (Taste): Kashaya (Astringent), Tikta; Guna: Laghu, Ruksha; Virya: Ushna (Warm); Vipaka: Katu",
            "traditional_uses": "Unripe fruit powder taken for diarrhea; ripe fruit pulp made into sweet summer drinks ('Bel Sharbat') to cool heat; trifoliate leaves offered to Lord Shiva.",
            "modern_uses": "Sold as bowel health powders, organic juices, diabetes supplements, and dietary fiber capsules.",
            "dosha_vata": 25,  # Balances Vata (calms intestinal spasming)
            "dosha_pitta": 30, # Ripe fruit balances Pitta; unripe leaves/root balance Pitta
            "dosha_kapha": 20, # Balances Kapha due to dry and astringent properties
            "strength_immunity": 80,
            "strength_anti_inflammatory": 78,
            "strength_digestive": 98,
            "strength_respiratory": 50,
            "climate_requirements": "Dry, subtropical, and tropical climates. Can tolerate temperature extremes.",
            "soil_requirements": "Loamy, clayey or stony soils. Tolerates water logging or dry spells.",
            "water_requirements": "Moderate water. Drought resistant once tree matures.",
            "sunlight_requirements": "Full sun.",
            "growth_conditions": "Thorny tree growing up to 10 meters. Slow-growing; fruits take a full year to mature.",
            "precautions": "Ripe fruit pulp is a mild laxative; unripe pulp binds bowels. Choose the correct format for your symptoms.",
            "side_effects": "Excessive intake of unripe powder can cause temporary constipation.",
            "contraindications": "None significant. Safe during lactation.",
            "recommended_usage": "Fruit pulp juice: 50-100 ml; Dry powder of unripe fruit: 3-6 grams daily.",
            "historical_significance": "The tree is considered sacred to Lord Shiva. Its leaves represent the three eyes of Shiva and are placed on Shivalingas.",
            "ayurvedic_importance": "Included in the Dashamula (ten sacred roots) formula; invaluable for treating chronic colitis and digestive malabsorption (Grahani).",
            "cultural_relevance": "Sipping Bel Sharbat during summer is a popular household remedy to prevent heat strokes across India."
        },
        {
            "name": "Arjuna",
            "scientific_name": "Terminalia arjuna",
            "sanskrit_name": "Arjuna",
            "telugu_name": "Tella Maddi",
            "hindi_name": "Arjun",
            "family": "Combretaceae",
            "native_region": "Riverbeds of Central and Southern India",
            "uses": "Cardiovascular strength, blood pressure control, heart muscle rejuvenation, and cholesterol management.",
            "description": "Arjuna is a majestic riverine tree with smooth gray bark. The red bark of the tree is the most famous cardio-protective herb in Ayurveda, used for centuries to strengthen cardiac muscles and regulate blood circulation.",
            "category": "heart",
            "ayurvedic_classification": "Hridya (Cardio-tonic), Sandhaniya (Healing/union of fractures), Shonitasthapana (Stops bleeding)",
            "ayurvedic_properties": "Rasa (Taste): Kashaya (Astringent); Guna: Ruksha, Laghu; Virya: Sheeta (Cold); Vipaka: Katu",
            "traditional_uses": "Bark powder boiled in milk and water ('Arjuna Ksheerapaka') taken daily to strengthen the heart, reduce angina, and repair bone fractures.",
            "modern_uses": "Used in heart-care tablets, blood pressure management capsules, herbal teas, and cholesterol supplements.",
            "dosha_vata": 40,  # Balances Vata in moderate doses with milk
            "dosha_pitta": 15, # Cools Pitta (lowers inflammatory blood heat)
            "dosha_kapha": 20, # Pacifies Kapha (scrapes fat/plaque from arteries)
            "strength_immunity": 84,
            "strength_anti_inflammatory": 85,
            "strength_digestive": 60,
            "strength_respiratory": 70,
            "climate_requirements": "Humid and tropical environments. Thrives near watercourses or marshy banks.",
            "soil_requirements": "Moist, alluvial loam soils. Needs moisture in the sub-soil.",
            "water_requirements": "High water needs for young saplings. Prefers riverbeds.",
            "sunlight_requirements": "Full sun to partial shade.",
            "growth_conditions": "Large evergreen tree reaching up to 25 meters. Bark naturally peels off and is collected without cutting down the tree.",
            "precautions": "Astringent taste. Do not take in dry format without milk/water as it can cause mild dryness in mouth.",
            "side_effects": "None reported in recommended clinical doses.",
            "contraindications": "None. Highly compatible with conventional cardiovascular drugs (consult doctor).",
            "recommended_usage": "Bark powder: 3-6 grams; Bark decoction in milk: 50-100 ml; Liquid extract: 15-30 ml.",
            "historical_significance": "Mentioned in Rig Veda; Vagbhata was the first to describe its use for heart disease in ancient medical records.",
            "ayurvedic_importance": "The ultimate cardiotonic that nourishes the heart physically and emotionally (calms grief and anxiety).",
            "cultural_relevance": "Represents protection, strength, and unwavering heart health in traditional medicine."
        },
        {
            "name": "Gudmar",
            "scientific_name": "Gymnema sylvestre",
            "sanskrit_name": "Gudmar / Madhunashini",
            "telugu_name": "Podapatri",
            "hindi_name": "Gudmar",
            "family": "Apocynaceae",
            "native_region": "Tropical forests of Central and Southern India",
            "uses": "Diabetes support, sugar craving suppression, weight loss, and pancreas rejuvenation.",
            "description": "Gudmar is a woody climbing plant whose name literally translates to 'Sugar Destroyer'. Chewing the leaves temporarily paralyzes the taste buds' capacity to taste sweet things, making it a powerful weapon against sugar cravings and diabetes.",
            "category": "diabetes",
            "ayurvedic_classification": "Madhuravinashini (Destroyer of sweetness), Chakshushya (Good for eyes), Deepana (Appetizer)",
            "ayurvedic_properties": "Rasa (Taste): Kashaya (Astringent), Tikta (Bitter); Guna: Laghu, Ruksha; Virya: Ushna; Vipaka: Katu",
            "traditional_uses": "Dry leaf powder taken before meals to reduce carbohydrate absorption and stimulate insulin release from the pancreas; fresh leaves chewed to stop sweet cravings.",
            "modern_uses": "Used in sugar management formulas, weight-loss teas, and insulin-regulating capsules.",
            "dosha_vata": 45,  # Can increase Vata if overused due to dry/bitter nature
            "dosha_pitta": 30, # Neutral to Pitta
            "dosha_kapha": 15, # Strongly pacifies Kapha (reduces fat and sweet tissue cravings)
            "strength_immunity": 80,
            "strength_anti_inflammatory": 82,
            "strength_digestive": 85,
            "strength_respiratory": 40,
            "climate_requirements": "Warm, tropical, and subtropical forest areas.",
            "soil_requirements": "Well-drained, sandy-loam soils. Can grow in dry regions if watered.",
            "water_requirements": "Moderate water. Keep soil slightly moist during growing season.",
            "sunlight_requirements": "Partial shade to full sun. Needs climbing support.",
            "growth_conditions": "Woody climber. Leaves are collected during dry autumn seasons.",
            "precautions": "May cause hypoglycemia (low blood sugar) if taken in massive doses alongside insulin. Monitor levels.",
            "side_effects": "Mild temporary loss of sweet taste sensation (lasts 1-2 hours).",
            "contraindications": "None known. Safe in dietary levels.",
            "recommended_usage": "Leaf powder: 2-3 grams twice daily before meals; Liquid extract: 5-10 ml.",
            "historical_significance": "Sanskrit texts describe how the leaf blocks sweetness, documented in Sushruta Samhita for treating 'Madhumeha' (sweet urine/diabetes).",
            "ayurvedic_importance": "Restores pancreas strength and balances the sweet taste (Madhura Rasa) imbalance in the body.",
            "cultural_relevance": "Praised in folk medicine as a miraculous remedy for metabolic diseases."
        },
        {
            "name": "Vasaka",
            "scientific_name": "Adhatoda vasica",
            "sanskrit_name": "Vasaka / Adhatoda",
            "telugu_name": "Addasaram",
            "hindi_name": "Adusa / Vasaka",
            "family": "Acanthaceae",
            "native_region": "Indian plains and lower Himalayan foothills",
            "uses": "Asthma, bronchitis, chronic cough, tuberculosis support, and respiratory clearing.",
            "description": "Vasaka is a tall, dense evergreen shrub with large leaves. It contains vasicine, which is a powerful natural bronchodilator and expectorant, making it the premier Ayurvedic plant for respiratory health.",
            "category": "respiratory",
            "ayurvedic_classification": "Kasahara (Relieves cough), Shvasahara (Relieves asthma), Rakta-Pitta Hara (Cools blood bleeding)",
            "ayurvedic_properties": "Rasa (Taste): Tikta, Kashaya; Guna: Laghu, Ruksha; Virya: Sheeta; Vipaka: Katu",
            "traditional_uses": "Fresh leaf juice mixed with honey administered for asthma attacks and wet coughs; leaves boiled to make steam inhalation for chest congestion.",
            "modern_uses": "Formulated in organic cough syrups, bronchodilating capsules, and throat lozenges.",
            "dosha_vata": 60,  # Can increase Vata slightly in long-term use due to drying nature
            "dosha_pitta": 15, # Cools Pitta (highly effective in bleeding disorders and lung heat)
            "dosha_kapha": 10, # Strongly pacifies Kapha (liquefies and expels thick mucus)
            "strength_immunity": 85,
            "strength_anti_inflammatory": 88,
            "strength_digestive": 55,
            "strength_respiratory": 99,
            "climate_requirements": "Subtropical and tropical climates. Grows easily in wild waste lands.",
            "soil_requirements": "Grows well in sandy-loam, dry, poor soils. Highly adaptive.",
            "water_requirements": "Low to moderate water. Drought tolerant.",
            "sunlight_requirements": "Requires full sun.",
            "growth_conditions": "Evergreen shrub growing up to 2-3 meters. Propagated easily from stem cuttings.",
            "precautions": "Strong taste. Always take with honey to soothe throat and mask bitterness.",
            "side_effects": "Very high doses may cause vomiting or throat irritation.",
            "contraindications": "Avoid during pregnancy as vasicine can stimulate mild uterine contraction.",
            "recommended_usage": "Fresh leaf juice: 5-10 ml with honey; Leaf decoction: 15-30 ml daily.",
            "historical_significance": "Praised in ancient texts: 'No one with respiratory diseases need despair as long as the Vasaka plant is around'.",
            "ayurvedic_importance": "The most effective herbal expectorant that dilates airways and reduces lung heat.",
            "cultural_relevance": "Grown along hedges of rural households across India as a first-line remedy for family colds."
        },
        {
            "name": "Sarpagandha",
            "scientific_name": "Rauvolfia serpentina",
            "sanskrit_name": "Sarpagandha",
            "telugu_name": "Sarpagandha / Patala Garuda",
            "hindi_name": "Sarpagandha",
            "family": "Apocynaceae",
            "native_region": "Sub-Himalayan wet forests of India",
            "uses": "Hypertension, blood pressure control, insomnia, anxiety, and snake bites.",
            "description": "Sarpagandha, also known as 'Indian Snakeroot', is a rare medicinal shrub. Its roots contain reserpine, which was the world's first modern drug to treat hypertension and schizophrenia, acting as a deep sedative and nervous system relaxant.",
            "category": "rare",
            "ayurvedic_classification": "Nidrajanana (Induces sleep), Raktavata Shamana (Hypotensive), Vishaghna (Antidote to poison)",
            "ayurvedic_properties": "Rasa (Taste): Tikta; Guna: Ruksha; Virya: Ushna (Warm); Vipaka: Katu",
            "traditional_uses": "Root powder administered in small doses to violent psychiatric patients, insomniacs, and those suffering from dangerously high blood pressure.",
            "modern_uses": "Isolated alkaloids are used in pharmaceutical drugs for blood pressure and nervous sedatives.",
            "dosha_vata": 20,  # Highly pacifies hyper-Vata (settles racing mind)
            "dosha_pitta": 25, # Neutralizes excess Pitta anger/anxiety
            "dosha_kapha": 30, # Balances Kapha due to bitter/hot nature
            "strength_immunity": 70,
            "strength_anti_inflammatory": 75,
            "strength_digestive": 50,
            "strength_respiratory": 40,
            "climate_requirements": "Warm, humid, tropical forest environments with high rainfall.",
            "soil_requirements": "Deep, loose, fertile clay-loamy soils rich in humus.",
            "water_requirements": "Requires consistent watering. Cannot tolerate dry droughts.",
            "sunlight_requirements": "Prefers partial shade or filtered forest light.",
            "growth_conditions": "Small woody shrub. Highly endangered in the wild due to over-harvesting; now cultivated under strict regulation.",
            "precautions": "Potent herb. Should never be self-administered without a certified Ayurvedic doctor's diagnosis.",
            "side_effects": "Can cause nasal congestion, low heart rate, and fatigue if taken in wrong dosage.",
            "contraindications": "Strictly contraindicated in depression, stomach ulcers, and pregnancy.",
            "recommended_usage": "Root powder: 250 mg to 1 gram daily under strict medical supervision.",
            "historical_significance": "Chewed by Mahatma Gandhi to soothe anxiety and calm his mind during high-stress negotiation periods.",
            "ayurvedic_importance": "Praised as the supreme 'Raktavata' pacifier, reducing high blood pressure instantly.",
            "cultural_relevance": "Its snake-like winding roots gave rise to its Sanskrit name, symbolizing its traditional use against snake and insect bites."
        },
        {
            "name": "Haritaki",
            "scientific_name": "Terminalia chebula",
            "sanskrit_name": "Haritaki / Abhaya",
            "telugu_name": "Karakkaya",
            "hindi_name": "Harad / Haritaki",
            "family": "Combretaceae",
            "native_region": "Indian Subcontinent",
            "uses": "Constipation relief, digestion improvement, brain health, and detoxification.",
            "description": "Haritaki is a large deciduous tree. Its dried fruits are considered the 'King of Medicine' in Tibet. It is a powerful mild laxative, liver detoxifier, and brain revitalizer, serving as one of the three components of the famous Triphala formula.",
            "category": "digestion",
            "ayurvedic_classification": "Tridosha Hara (Balances Vata, Pitta, Kapha), Anulomana (Directs digestive wind downwards), Rasayana",
            "ayurvedic_properties": "Rasa (Taste): Has 5 tastes except salty, predominantly Kashaya (Astringent) and Tikta; Guna: Laghu, Ruksha; Virya: Ushna (Warm); Vipaka: Madhura",
            "traditional_uses": "Powder taken with warm water at night for regular bowels; mixed with salt for Kapha, sugar for Pitta, and ghee for Vata.",
            "modern_uses": "Used in colon cleanse supplements, Triphala tablets, hair powders, and digestive syrups.",
            "dosha_vata": 15,  # Highly pacifies Vata due to sweet post-digestive effect
            "dosha_pitta": 20, # Balances Pitta due to rejuvenative qualities
            "dosha_kapha": 15, # Balances Kapha due to dry/astringent properties
            "strength_immunity": 90,
            "strength_anti_inflammatory": 85,
            "strength_digestive": 99,
            "strength_respiratory": 75,
            "climate_requirements": "Subtropical to tropical environments. Thrives on dry slopes.",
            "soil_requirements": "Clayey, loamy or gravelly soils that drain water easily.",
            "water_requirements": "Low to moderate watering.",
            "sunlight_requirements": "Requires full sun.",
            "growth_conditions": "Deciduous tree growing up to 15-20 meters. Fruits are harvested when they turn green-yellow.",
            "precautions": "Mildly purgative. Drink plenty of water when consuming.",
            "side_effects": "High doses may cause mild diarrhea or dehydration.",
            "contraindications": "Avoid in severe exhaustion, severe dehydration, or pregnancy.",
            "recommended_usage": "Fruit powder: 3-5 grams daily with warm water at bedtime.",
            "historical_significance": "Medicine Buddha is traditionally depicted holding a branch of the Haritaki plant in his hand, symbolizing universal healing.",
            "ayurvedic_importance": "Known as 'Abhaya' (fearless) because it removes the fear of disease by balancing all bodily systems.",
            "cultural_relevance": "Eaten as a daily digestive aid by millions in Indian households."
        },
        {
            "name": "Bibhitaki",
            "scientific_name": "Terminalia bellirica",
            "sanskrit_name": "Bibhitaki / Vibhidaka",
            "telugu_name": "Thanikaya",
            "hindi_name": "Baheda / Bibhitaki",
            "family": "Combretaceae",
            "native_region": "Indian Subcontinent plains and forests",
            "uses": "Cough, throat infection, asthma, hair health, and eyes.",
            "description": "Bibhitaki is a large deciduous tree whose name means 'fearless of disease'. It is the second component of Triphala, specialized in clearing mucus, clearing throat irritation, supporting eyesight, and preventing grey hair.",
            "category": "respiratory",
            "ayurvedic_classification": "Kanthya (Good for throat), Kasahara (Cough reliever), Chakshushya (Eye toner)",
            "ayurvedic_properties": "Rasa (Taste): Kashaya (Astringent); Guna: Ruksha, Laghu; Virya: Ushna (Warm); Vipaka: Katu",
            "traditional_uses": "Roasted fruit skin chewed for sore throat and dry cough; powder mixed with honey to clear chest congestion; paste applied to hair roots.",
            "modern_uses": "Used in throat lozenges, cough remedies, hair oil blends, and Triphala formulations.",
            "dosha_vata": 40,  # Neutral to Vata
            "dosha_pitta": 35, # Neutral to Pitta
            "dosha_kapha": 10, # Strongly pacifies Kapha (expels lung mucus)
            "strength_immunity": 85,
            "strength_anti_inflammatory": 80,
            "strength_digestive": 75,
            "strength_respiratory": 96,
            "climate_requirements": "Moist forest slopes and plains of subtropical regions.",
            "soil_requirements": "Sandy-loam, moist soils with good organic matter.",
            "water_requirements": "Moderate water.",
            "sunlight_requirements": "Requires full sun.",
            "growth_conditions": "Large forest tree. Tends to attract birds and wildlife. Fruits collected in dry seasons.",
            "precautions": "Astringent action. Always mix dry powder with honey or warm water.",
            "side_effects": "Dry mouth if taken without liquid.",
            "contraindications": "None significant. Do not consume seeds directly.",
            "recommended_usage": "Powder: 2-3 grams twice daily with honey or warm water.",
            "historical_significance": "Documented in Charaka Samhita as the premier herb for throat clearing and voice enhancement.",
            "ayurvedic_importance": "Specialized in scraping fat (Meda Dhatu) and drying up sticky Kapha toxins from the chest.",
            "cultural_relevance": "An ancient forest tree widely grown in traditional Indian villages."
        },
        {
            "name": "Kalmegh (King of Bitters)",
            "scientific_name": "Andrographis paniculata",
            "sanskrit_name": "Kalamegha",
            "telugu_name": "Nelavemu",
            "hindi_name": "Kalmegh",
            "family": "Acanthaceae",
            "native_region": "India and Sri Lanka",
            "uses": "Liver protection, chronic fevers, blood purification, common cold, and immune defense.",
            "description": "Kalmegh is known as the 'King of Bitters' due to its extremely bitter taste. In Ayurvedic medicine, it is highly valued for its hepatoprotective (liver protecting), anti-inflammatory, and immunostimulant properties, making it an excellent remedy for digestive and respiratory ailments.",
            "category": "medicinal_herbs",
            "ayurvedic_classification": "Yakrid-Uttejana (Liver stimulant), Jvarahara (Fever reducer), Krimighna (Antiparasitic)",
            "ayurvedic_properties": "Rasa (Taste): Tikta (Bitter); Guna (Physical Property): Laghu (Light), Ruksha (Dry); Virya (Potency): Ushna (Warm); Vipaka (Post-digestive effect): Katu (Pungent)",
            "traditional_uses": "Used traditionally in decoctions to treat sluggish liver, loss of appetite, acute fevers, respiratory infections, and intestinal worms.",
            "modern_uses": "Commonly used in modern liver care supplements, immune-boosting syrups, and formulations for common cold and flu support.",
            "dosha_vata": 60,
            "dosha_pitta": 20,
            "dosha_kapha": 15,
            "strength_immunity": 90,
            "strength_anti_inflammatory": 85,
            "strength_digestive": 88,
            "strength_respiratory": 80,
            "climate_requirements": "Tropical and subtropical climates. Requires warm temperatures with moderate humidity.",
            "soil_requirements": "Well-drained sandy loam or clayey soils rich in organic matter.",
            "water_requirements": "Regular watering. Prefers moist soil but cannot tolerate waterlogging.",
            "sunlight_requirements": "Requires partial shade to full sun.",
            "growth_conditions": "Grows easily in home gardens, pots, and agricultural fields as an annual herb.",
            "precautions": "Extremely bitter taste. Avoid overuse as it may cause gastric irritation or loss of appetite.",
            "side_effects": "None in standard doses; high doses may cause mild nausea.",
            "contraindications": "Avoid during pregnancy as it may stimulate uterine contractions.",
            "recommended_usage": "Leaf decoction: 10-20 ml; Powder: 1-3 grams daily with honey to mask bitterness.",
            "historical_significance": "Used for centuries in traditional Siddha and Ayurvedic medicine across the Indian subcontinent.",
            "ayurvedic_importance": "One of the most potent bitter herbs for cooling liver heat (Pitta) and clearing deep-seated toxins (Ama).",
            "cultural_relevance": "Known in rural India as a reliable household remedy for childhood fevers and digestive issues."
        },
        {
            "name": "Gokshura (Small Caltrops)",
            "scientific_name": "Tribulus terrestris",
            "sanskrit_name": "Gokshura",
            "telugu_name": "Palleru Kaaya",
            "hindi_name": "Gokhru",
            "family": "Zygophyllaceae",
            "native_region": "Warm regions of Southern Europe, Asia, Africa, and Australia",
            "uses": "Men's vitality, muscle strength, kidney health, urinary support, and hormone balance.",
            "description": "Gokshura is a creeping perennial herb with small yellow flowers and sharp, thorny fruits. It is the premier rejuvenative herb for the male reproductive and urinary systems in Ayurveda, famous for boosting energy, stamina, and kidney function.",
            "category": "mens_health",
            "ayurvedic_classification": "Vajikarana (Aphrodisiac), Balya (Strength promoter), Rasayana (Rejuvenative), Mootrala (Diuretic)",
            "ayurvedic_properties": "Rasa (Taste): Madhura (Sweet); Guna: Guru (Heavy), Snigdha (Unctuous); Virya: Sheeta (Cold); Vipaka: Madhura",
            "traditional_uses": "Root and fruit powder boiled in milk is taken to improve male fertility, strengthen the kidneys, relieve painful urination, and treat kidney stones.",
            "modern_uses": "Widely formulated in modern sports supplements for boosting testosterone levels naturally, improving athletic performance, and urinary tract health.",
            "dosha_vata": 15,
            "dosha_pitta": 20,
            "dosha_kapha": 65,
            "strength_immunity": 85,
            "strength_anti_inflammatory": 78,
            "strength_digestive": 60,
            "strength_respiratory": 55,
            "climate_requirements": "Arid to semi-arid climates. Warm temperatures with low rainfall.",
            "soil_requirements": "Loose, sandy, or gravelly well-draining soils. Highly resilient to poor soils.",
            "water_requirements": "Low water needs. Extremely drought tolerant.",
            "sunlight_requirements": "Requires full, direct sunlight.",
            "growth_conditions": "Low creeping plant. Grows wild along dry roadsides, pastures, and sandy plains.",
            "precautions": "Thorny fruits can cause physical injury. Use commercially prepared clean powders.",
            "side_effects": "None in standard doses; may cause mild stomach warmness if taken on empty stomach.",
            "contraindications": "Avoid in cases of severe dehydration or acute prostate congestion without professional supervision.",
            "recommended_usage": "Fruit powder: 3-6 grams daily with warm milk or water; Decoction: 50-100 ml.",
            "historical_significance": "Described in Charaka Samhita as a crucial component of rejuvenative (Rasayana) therapies and strength building.",
            "ayurvedic_importance": "One of the key herbs in the Dashamula (ten roots) formulation, highly prized for balancing Vata and strengthening reproductive fluids.",
            "cultural_relevance": "Historically praised in Indian folk medicine as the 'strength of the bull' due to its powerful energy-boosting properties."
        },
        {
            "name": "Shankhpushpi",
            "scientific_name": "Convolvulus pluricaulis",
            "sanskrit_name": "Shankhapushpi",
            "telugu_name": "Shankhapushpi",
            "hindi_name": "Shankhpushpi",
            "family": "Convolvulaceae",
            "native_region": "India and Myanmar",
            "uses": "Brain power, memory enhancement, nervous system calming, anxiety relief, and sleep support.",
            "description": "Shankhpushpi is a perennial herb with conch-shaped white or purple flowers. It is the premier 'Medhya Rasayana' (brain tonic) in Ayurveda, known for its ability to enhance memory, concentration, and intellect, while calming the mind and reducing stress.",
            "category": "traditional",
            "ayurvedic_classification": "Medhya (Intellect promoter), Nidrajanana (Sleep inducer), Majja-Dhatu-Rasayana (Nervous rejuvenative)",
            "ayurvedic_properties": "Rasa (Taste): Tikta (Bitter); Guna: Sar (Mobility), Snigdha; Virya: Sheeta (Cold); Vipaka: Madhura",
            "traditional_uses": "The whole plant juice or paste is administered to students and children to boost learning capability, memory, and to treat sleeplessness and mental fatigue.",
            "modern_uses": "Used in organic memory boosters, cognitive health syrups, anxiety supplements, and stress-relief teas.",
            "dosha_vata": 20,
            "dosha_pitta": 15,
            "dosha_kapha": 30,
            "strength_immunity": 78,
            "strength_anti_inflammatory": 70,
            "strength_digestive": 65,
            "strength_respiratory": 50,
            "climate_requirements": "Subtropical to tropical arid climates. Resilient to high heat.",
            "soil_requirements": "Sandy, rocky, or well-drained soils. Grows well in wild dry grasslands.",
            "water_requirements": "Low water needs once established.",
            "sunlight_requirements": "Requires full, direct sunlight.",
            "growth_conditions": "Small creeping herb with branches spreading on the ground. Can be grown in pots and rock gardens.",
            "precautions": "May lower blood pressure slightly. Monitor if on antihypertensive medications.",
            "side_effects": "None reported in recommended clinical doses.",
            "contraindications": "Avoid if suffering from severe hypotension (low blood pressure).",
            "recommended_usage": "Fresh juice: 10-20 ml; Whole plant powder: 3-6 grams daily with milk or warm water.",
            "historical_significance": "Described by ancient sage Charaka as the best herb for improving intellect and mental acuity.",
            "ayurvedic_importance": "Balances the sadhaka pitta (which controls emotions and intellect) and prana vayu (which controls mental focus).",
            "cultural_relevance": "Named after the 'Shankha' (sacred conch shell) due to the flower's shape, representing purity, auspiciousness, and wisdom in Indian culture."
        }
    ]

    for p in plants_data:
        Plant.objects.create(**p)

    print(f"✨ Successfully seeded {len(plants_data)} detailed Ayurvedic plants!")

if __name__ == "__main__":
    seed_plants()